exterior (parking and entry canopy) lighting power density update
NREL/openstudio-standards pull request #1000
Opened 2021-01-08 01:19 UTC by JanghyunJK

- parking LPD updated based on values derived from [2015 LMC report](https://www.energy.gov/eere/ssl/2015-us-lighting-market-characterization)

- entry canopy LPD was also udpated based on updates already made on DEER pre1975 to 1996

- refer to [summary slide deck](https://nrel.sharepoint.com/:p:/r/sites/LoadProfiles/Shared%20Documents/05%20Calibration/4%20Calibration%20and%20Validation/ComStock_Lighting_Analysis/LightingPowerDensity/201207_ExteriorLightingPowerDensityFromDataSources.pptx?d=we753e224cdc04daea774e80bf4409a63&csf=1&web=1&e=0beiZO) for details

2021-01-09 00:12 UTC, mdahlhausen commented
Thanks @JanghyunJK. This looks good.  Should [this line](https://github.com/NREL/openstudio-standards/blob/b04a2ef2c4403f1a45464e2010b7f6862b9e1fd9/lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.ext_ltg.json#L133) be 90.1-2013, not 90.1-2012?

2021-01-09 00:13 UTC, mdahlhausen requested changes
Just fix the [note text here](https://github.com/NREL/openstudio-standards/blob/b04a2ef2c4403f1a45464e2010b7f6862b9e1fd9/lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.ext_ltg.json#L133) and I'll merge it.

2021-01-09 00:22 UTC, JanghyunJK commented
> Thanks @JanghyunJK. This looks good. Should [this line](https://github.com/NREL/openstudio-standards/blob/b04a2ef2c4403f1a45464e2010b7f6862b9e1fd9/lib/openstudio-standards/standards/ashrae_90_1/doe_ref_pre_1980/comstock_doe_ref_pre_1980/data/comstock_doe_ref_pre_1980.ext_ltg.json#L133) be 90.1-2013, not 90.1-2012?

interesting. that note is actually what was already there (and not my input) in [this line](https://docs.google.com/spreadsheets/d/1t1Jx2o-XnxNjYgp5uXN0Wr4oh8ZNfTfMf_2jb3_BopI/edit#gid=835825994&range=32:32) of the os standard. but since you pointed out, notes under ```ComStock DOE Ref 1980-2004``` & ```ComStock DOE Ref Pre-1980``` templates are definitely weird using years when standards were not published.

my guess is that they all should be referencing 2004 (and error caused from dragging which resulted in values in series??). if you agree, I'll make changes and re-pull-request.


--

2021-01-11 16:42 UTC, JanghyunJK commented
@mdahlhausen 
- typos in Notes were fixed
- and another typo in column header was fixed as well.

2021-01-11 17:51 UTC, merged