ASHRAE 62.1 Simplified Procedure
NREL/openstudio-standards pull request #1112
Opened 2021-06-21 18:41 UTC by lymereJ

The proposed changes update the method to calculate the minimum damper position and system design outdoor air based on the ASHRAE 62.1 Simplified Procedure (as opposed to the method in Appendix A) as required by ASHRAE 90.1-2019. Additional information regarding the implementation are provided in Section B2.7 in the [Energy Savings Analysis: ANSI/ASHRAE/IES Standard 90.1-2019 report](https://www.energycodes.gov/sites/default/files/documents/20210407_Standard_90.1-2019_Determination_TSD.pdf).

The proposed changes also improve the existing method by letting EnergyPlus size the system outdoor air intake based on a minimum zone ventilation of 0.6 (not possible before OS 3.0, follow up on the issue identified in #776), and remove redundant code.

2021-09-07 20:10 UTC, lymereJ commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/ashrae_90_1_2010.AirLoopHVAC.rb
> -
Remove redundant code.

2021-09-07 20:12 UTC, lymereJ commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.AirLoopHVAC.rb
> +  end
New method that sets the MDP based on `v_oz` and `v_ot` based on a simplified `e_v` calculation.

2021-09-07 20:14 UTC, lymereJ commented on lib/openstudio-standards/prototypes/common/objects/Prototype.SizingSystem.rb
> +      sizing_zone.setDesignMinimumZoneVentilationEfficiency(0.6)
Sets the minimum `e_vz` which wasn't possible prior to OS 3.0.

2021-09-13 21:02 UTC, mdahlhausen requested changes
- Add log/warning message for method that isn't supported for OS versions < 3.0 (add version check in code).
- check alignment between system outdoor air method in sizing system and controller mechanical ventilation

2021-09-14 18:27 UTC, lymereJ commented
> * Add log/warning message for method that isn't supported for OS versions < 3.0 (add version check in code).
> * check alignment between system outdoor air method in sizing system and controller mechanical ventilation

I added a warning for the unsupported method.

As I expected, the fact that the controller mechanical ventilation is created by default and cannot be unassigned from the controller outdoor air (unless I'm mistaken) can potentially be an issue because if the OA flow rate specified at the sizing system level is lower than what is recalculated by the controller mechanical ventilation using the "zone sum" approach, the later is used during the simulation. Since this is can be an issue now, and will be if this PR is merged, I would be inclined to merge it as is, file an issue on the OpenStudio Github page, and reference this PR. What do you think?

2021-09-14 21:06 UTC, mdahlhausen approved these changes

2021-09-14 21:06 UTC, merged