fix an error in the secondary school geometry file
NREL/openstudio-standards pull request #1144
Opened 2021-07-16 21:30 UTC by yunyangye

Fix the issue posted in [#1132 ](https://github.com/NREL/openstudio-standards/issues/1132).

2021-07-16 22:05 UTC, lymereJ approved these changes

2021-07-20 15:43 UTC, mdahlhausen commented
Update the regression tests with OS 3.0; the OS 3.2 tests will fail (for now).  If the older version regression tests pass, I'll merge this.

2021-07-20 15:44 UTC, mdahlhausen requested changes
re-generate regression model in OS 3.0

2021-07-29 16:26 UTC, mdahlhausen requested changes
regression tests still failing

2021-07-30 22:41 UTC, merged