901 2016 2019 add ce ay erv
NREL/openstudio-standards pull request #1165
Opened 2021-08-17 22:47 UTC by yunyangye

Based on 90.1-2019 Addendum AY, this PR updates the implementing method about ERV for dwelling units. While Addendum AY specifies the enthalpy recovery ratio (ERR) requirements for ERVs, the energy simulations require inputs in terms of heat recovery effectiveness. This PR translates the EER values to effectiveness and insert the new effectiveness into zone ERV. This implementation affects the prototype models for 90.1-2019 mid-rise and high-rise apartments.

2021-08-20 19:52 UTC, yunyangye commented on data/standards/manage_OpenStudio_Standards.rb
> +           ['template', 'climate_zone', 'under_8000_hours', 'nontransient_dwelling']
OpenStudio_Standards-ashrae_90_1 table was changed. The new column, 'Nontransient Dwelling', in 'Energy Recovery' tab becomes one of search criteria.

2021-08-20 19:53 UTC, yunyangye commented on data/standards/manage_OpenStudio_Standards.rb
> +  bool_cols << 'nontransient_dwelling'
This new column in the spreadsheet is bool format.

2021-08-20 19:54 UTC, yunyangye commented on lib/openstudio-standards.rb
> +  require_relative "#{proto}/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.HeatExchangerAirToAirSensibleAndLatent"
A new ruby file was created about heat exchanger calculation for ASHRAE 90.1-2019. Thus, the require_relative for this file was added.

2021-08-20 19:58 UTC, yunyangye commented on lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.HeatExchangerAirToAirSensibleAndLatent.rb
> +end
This new file is to set sensible and latent effectiveness for air-to-air heat exchanger based on Enthalpy Recovery Ratio (ERR). This function in the file is only used for the 90.1-2019 high- and mid-rise apartment.

2021-08-20 20:02 UTC, yunyangye commented on lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.Model.rb
> +  end
This function is used to check if zone ERV needs to be added, the search criteria if ERV is needed, and add ERV. The zone ERV is only considered for the 90.1-2019 high- and mid-rise apartment.

2021-08-20 20:03 UTC, yunyangye commented on lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.hvac_systems.rb
> +  end
This function is used to add zone ERV based on ERR. This function is only used for the 90.1-2019 high- and mid-rise apartment.

2021-08-20 20:04 UTC, yunyangye commented on lib/openstudio-standards/standards/Standards.HeatExchangerSensLat.rb
> +    return full_htg_sens_eff, full_htg_lat_eff, part_htg_sens_eff, part_htg_lat_eff, full_cool_sens_eff, full_cool_lat_eff, part_cool_sens_eff, part_cool_lat_eff
These two functions are used to transfer ERR into effectiveness for heat exchanger.

2021-08-24 18:03 UTC, lymereJ commented on lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.Model.rb
> +  def model_apply_prototype_hvac_efficiency_adjustments(model)
I'm a little bit concern about making this function template specific. I don't think that the aim of this function is to be specific to energy recovery. I'd suggest to wrap the current code in the main `model_apply_prototype_hvac_efficiency_adjustments` method, which deals only with heat exchangers mods, in one method and make that method template specific. This way if someone adds code to `model_apply_prototype_hvac_efficiency_adjustments` that unrelated to heat exchangers, they don't have to add it to this function as well (in the main `else`).

2021-08-24 18:03 UTC, lymereJ commented on lib/openstudio-standards/standards/Standards.HeatExchangerSensLat.rb
> +    OpenStudio.logFree(OpenStudio::Info, 'openstudio.standards.HeatExchangerSensLat', "For #{heat_exchanger_air_to_air_sensible_and_latent.name}: Set sensible and latent effectiveness.")
Here, we're making the method more versatile and provide a terminology fix.

2021-09-08 19:17 UTC, yunyangye commented on lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.HeatExchangerAirToAirSensibleAndLatent.rb
> +  # This function is only used for nontransient dwelling units (Mid-rise and High-rise Apartment)
Addressed

2021-09-08 19:18 UTC, yunyangye commented on lib/openstudio-standards/prototypes/ashrae_90_1/ashrae_90_1_2019/ashrae_90_1_2019.Model.rb
> +  # This function is only used for nontransient dwelling units (Mid-rise and High-rise Apartment)
Addressed

2021-09-13 20:38 UTC, mdahlhausen commented on data/standards/manage_OpenStudio_Standards.rb
> +           ['template', 'minimum_capacity', 'maximum_capacity', 'start_date', 'end_date']
merge in the other commit for furnances to this pull request

2021-09-13 20:39 UTC, mdahlhausen commented on lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.schedules.json
> +      "name": "Always On - No DD",
Use full name 'Design Day' instead of DD

2021-09-13 20:39 UTC, mdahlhausen commented on lib/openstudio-standards/standards/ashrae_90_1/data/ashrae_90_1.schedules.json
> +      "name": "Always On - No DD",
'Design  Day' instead of 'DD'

2021-09-13 20:41 UTC, mdahlhausen commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/data/ashrae_90_1_2010.energy_recovery.json
> +      "err_basis": null,
use 'enthaply_recovery_ratio' instead of 'err'

2021-09-13 20:44 UTC, mdahlhausen commented on lib/openstudio-standards/standards/Standards.HeatExchangerSensLat.rb
> +  # @param basis [String] basis for effectiveness calculation, either cooling or heating
'cooling' or 'heating'

2021-09-13 20:50 UTC, mdahlhausen commented on lib/openstudio-standards/prototypes/common/objects/Prototype.HeatExchangerAirToAirSensibleAndLatent.rb
> +  # @param [String] err
parameters not fully explained / specified

2021-09-13 20:50 UTC, mdahlhausen commented on lib/openstudio-standards/prototypes/common/objects/Prototype.HeatExchangerAirToAirSensibleAndLatent.rb
> +  def heat_exchanger_air_to_air_sensible_and_latent_apply_prototype_efficiency_err(heat_exchanger_air_to_air_sensible_and_latent, err, basis, climate_zone)
even though the method name is long, avoid acronyms ('err') in method names

2021-09-13 20:52 UTC, mdahlhausen requested changes
- Minor naming changes - spell out enthalpy recovery ratio instead of 'err' in most cases
- Missing some comments on parameter documentation
- Added schedule should be 'Design Day' instead of 'DD'
- see other comments throughout

2021-09-14 05:44 UTC, lymereJ commented
@mdahlhausen - Just pushed a commit that addresses the review comments. Please note that there's an additional change: the type of system used by the midrise apartment model. It was original setup to use a split system AC but I ran into #1208 when wanting to change the constant volume fan to cycling. Using a PSZ-AC instead allow the fan to cycle to meet the load which is what we want: system to cycle to meet the load and ERV to provide constant OA with or without energy recovery.

2021-09-14 17:51 UTC, mdahlhausen approved these changes

2021-09-14 18:03 UTC, merged