Large office prototype computer room AC efficiency
NREL/openstudio-standards pull request #1200
Opened 2021-09-08 18:35 UTC by yunyangye

This PR updates the computer room AC efficiency for large office prototype model. This implementation affects the prototype models for large office. Additional information regarding the implementation are provided in Section B2.8 in the [Energy Savings Analysis: ANSI/ASHRAE/IES Standard 90.1-2019 report](https://www.energycodes.gov/sites/default/files/2021-07/20210407_Standard_90.1-2019_Determination_TSD.pdf).

2021-09-08 18:37 UTC, yunyangye commented on lib/openstudio-standards/prototypes/common/objects/Prototype.CoilCoolingWaterToAirHeatPumpEquationFit.rb
> +  end
Calculate CRAC efficiency based on SCOP and sensible cooling ratio.

2021-09-08 18:37 UTC, yunyangye commented on lib/openstudio-standards/prototypes/common/objects/Prototype.Model.rb
> +
Reset CRAC efficiency for large office prototype model.

2021-09-13 16:15 UTC, yunyangye commented on lib/openstudio-standards/prototypes/common/objects/Prototype.CoilCoolingWaterToAirHeatPumpEquationFit.rb
> +  end
Calculate CRAC efficiency based on SCOP and sensible heat ratio.

2021-09-13 19:03 UTC, mdahlhausen requested changes
This method sets efficiency for CoilCoolingWaterToAirHeatPumpEquationFit objects modding the `coil_cooling_water_to_air_heat_pump_standard_minimum_cop` method.  It looks up efficiency in new data tables in the `unitary_acs` data, but the method it is based on uses the `water_source_heat_pumps` data.  Instead of creating an entirely new method to set efficiency, adjust the existing method to take an optional argument and include the new data there.

coil_cooling_water_to_air_heat_pump

2021-09-14 00:35 UTC, lymereJ commented
`coil_cooling_water_to_air_heat_pump_standard_minimum_cop_crac` was moved to be part of `coil_cooling_water_to_air_heat_pump_standard_minimum_cop`.

2021-09-14 17:54 UTC, mdahlhausen approved these changes

2021-09-14 17:58 UTC, merged