College update w occupancy 2021 v2simplified
NREL/openstudio-standards pull request #1276
Opened 2022-03-02 20:47 UTC by ybae0330

Updated college building with updated occupancy schedule

2022-03-07 21:45 UTC, mdahlhausen requested changes
For some reason the prototype_inputs.json for doe ref version (pre-2004) are showing that all lines in the files changed.  Can revert the prototype_input.json files and only include changes for the college section?
Also, please remove the commented out templates and climate_zones lines in test_college.rb

2022-03-07 22:24 UTC, ybae0330 commented
> For some reason the prototype_inputs.json for doe ref version (pre-2004) are showing that all lines in the files changed. Can revert the prototype_input.json files and only include changes for the college section? Also, please remove the commented out templates and climate_zones lines in test_college.rb



> For some reason the prototype_inputs.json for doe ref version (pre-2004) are showing that all lines in the files changed. Can revert the prototype_input.json files and only include changes for the college section? Also, please remove the commented out templates and climate_zones lines in test_college.rb

Both issues are addressed and fixed!!
Thank you!

2022-03-08 00:38 UTC, mdahlhausen approved these changes

2022-03-18 16:08 UTC, mdahlhausen approved these changes

2022-03-18 16:08 UTC, merged