align oa requirements with energyplus prototypes
NREL/openstudio-standards pull request #1281
Opened 2022-03-15 16:10 UTC by wsjsxn

Align oa requirements with those of energyplus prototypes.

2022-03-21 21:52 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_area": 0.142855357,
Based on 30 cfm/room for a two room suite

2022-03-21 21:52 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_area": 0.142855357,
Based on 30 cfm/room for a two room suite

2022-03-21 21:55 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_area": 0.132557114,
Based on 35 cfm/bath

2022-03-21 21:57 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_area": 0.132611175,
Based on 35 cfm/bath

2022-03-25 22:15 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 15.0,
The value is wrong and the new value comes from 62.1.

2022-03-25 22:17 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 0.0,
The ventilation primary and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:18 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_area": 0.05,
The value was updated based on 62.1.

2022-03-25 22:21 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_area": 0.05,
The primary and secondary space types were corrected and the ventilation rates were updated accordingly.

2022-03-25 22:22 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 15.0,
The value is wrong and the new value was added based on 62.1

2022-03-25 22:23 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 15.0,
The value is wrong and the new value was added based on 62.1

2022-03-25 22:23 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 15.0,
The value is wrong and the new value was added based on 62.1

2022-03-25 22:23 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 15.0,
The value is wrong and the new value was added based on 62.1

2022-03-25 22:23 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 15.0,
The value is wrong and the new value was added based on 62.1

2022-03-25 22:23 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 15.0,
The value is wrong and the new value was added based on 62.1

2022-03-25 22:24 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2004/data/ashrae_90_1_2004.spc_typ.json
> +      "ventilation_per_person": 15.0,
The ventilation primary and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:24 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/data/ashrae_90_1_2007.spc_typ.json
> +      "ventilation_per_area": 0.085,
The ventilation standard was revised and the ventilation rates were updated accordingly.

2022-03-25 22:26 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2007/data/ashrae_90_1_2007.spc_typ.json
> +      "ventilation_per_person": 5.0,
The ventilation primary and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:26 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2010/data/ashrae_90_1_2010.spc_typ.json
> +      "ventilation_per_person": 5.0,
The ventilation primary and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:26 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/data/ashrae_90_1_2013.spc_typ.json
> +      "ventilation_per_area": 0.12,
The ventilation primary and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:26 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2013/data/ashrae_90_1_2013.spc_typ.json
> +      "ventilation_per_person": 5.0,
The ventilation primary and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:27 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/data/ashrae_90_1_2016.spc_typ.json
> +      "ventilation_per_area": 0.12,
The ventilation secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:27 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2016/data/ashrae_90_1_2016.spc_typ.json
> +      "ventilation_per_person": 5.0,
The ventilation primary and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:27 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.spc_typ.json
> +      "ventilation_per_area": 0.12,
The ventilation standard and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-25 22:27 UTC, wsjsxn commented on lib/openstudio-standards/standards/ashrae_90_1/ashrae_90_1_2019/data/ashrae_90_1_2019.spc_typ.json
> +      "ventilation_per_person": 5.0,
The ventilation primary and secondary space types were changed based on 62.1 and the corresponding ventilation rates were updated.

2022-03-29 15:59 UTC, mdahlhausen approved these changes
These updates look fine.

- Please regenerate the regression tests for the affected buildings
- There was an empty 'git' file added to the pull request.  Please remove it.

2022-03-29 17:34 UTC, mdahlhausen requested changes
changing to request changes until regression tests are updated

2022-04-02 05:42 UTC, wsjsxn commented
> These updates look fine.
> 
> * Please regenerate the regression tests for the affected buildings
> * There was an empty 'git' file added to the pull request.  Please remove it.

I have removed the empty git file and please review the changes. Thanks

2022-04-03 16:59 UTC, mdahlhausen approved these changes

2022-04-03 17:00 UTC, merged