Appendix g dev debug user directory error
NREL/openstudio-standards pull request #1407
Opened 2023-01-13 22:25 UTC by weilixu

2023-01-16 17:12 UTC, dmaddoxwhite approved these changes
Looks good!

2023-01-23 20:51 UTC, mdahlhausen commented on lib/openstudio-standards/standards/ashrae_90_1_prm/ashrae_90_1_prm.rb
> +
remove extra whitespace added

2023-01-23 20:51 UTC, mdahlhausen commented on test/90_1_prm/test_appendix_g_prm.rb
> +    assert(model, 'Unsuccessfully generating the model')
remove this assertion

2023-01-23 20:51 UTC, mdahlhausen requested changes
see comments

2023-01-25 00:31 UTC, weilixu commented
> see comments

@mdahlhausen  Updated based on comments

2023-01-27 20:04 UTC, mdahlhausen approved these changes

2023-01-27 20:04 UTC, merged