Refactor parametric schedules
NREL/openstudio-standards pull request #1718
Opened 2024-04-02 21:22 UTC by eringold

Pull request overview
---------------------

Refactors methods to better align model schedules with generated building hours of operation schedule and user inputs to `OpenstudioStandards::Schedules.schedule_ruleset_set_hours_of_operation` 

 - Fixes https://github.com/NREL/openstudio-standards/issues/1551, particularly that thermostat schedules aren't modified

### Pull Request Author

 - [x] Method changes or additions
 - [ ] Data changes or additions
 - [x] Added tests for added methods
 - [ ] If methods have been deprecated, update rest of code to use the new methods
 - [x] Documented new methods using [yard syntax](https://rubydoc.info/gems/yard/file/docs/GettingStarted.md)
 - [x] Resolved yard documentation errors for new code (ran `bundle exec rake doc`)
 - [x] Resolved rubocop syntax errors for new code (ran `bundle exec rake rubocop`)
 - [x] All new and existing tests passes
 - [ ] If the code adds new `require` statements, ensure these are in core ruby or add to the gemspec

### Review Checklist

This will not be exhaustively relevant to every PR.
 - [ ] Perform a code review on GitHub
 - [ ] All related changes have been implemented: method additions, changes, tests
 - [ ] Check rubocop errors
 - [ ] Check yard doc errors
 - [ ] If fixing a defect, verify by running develop branch and reproducing defect, then running PR and reproducing fix
 - [ ] If a new feature, test the new feature and try creative ways to break it
 - [ ] CI status: all green or justified

2024-04-04 17:00 UTC, mdahlhausen commented on lib/openstudio-standards/schedules/parametric.rb
> +          hoo_key = hours_of_operation.find { |_, val| val[:days_used].include?(day) }&.first
The &.method was introduced in Ruby 2.3. Is there a way you can generalize it to allow earlier Ruby versions? We still support older ruby versions in openstudio-standards for all but a few sizing methods.

2024-04-04 17:33 UTC, mdahlhausen requested changes
- Add unit tests to test_schedules_information.rb for these methods:
  - schedule_ruleset_get_annual_days_used
  - schedule_ruleset_get_schedule_day_rule_indices 
- Add unit tests to test_schedules_modify.rb for these methods:
  - schedule_day_populate_from_array_of_values
  - schedule_ruleset_create_rules_from_day_list
- These methods in schedules/parametric.rb need parameter descriptions for the yard documentation:
  - gather_inputs_parametric_space_space_type_schedules
  - gather_inputs_parametric_schedules

2024-04-05 17:55 UTC, eringold commented
@mdahlhausen all requested changes have been made.

2024-04-05 18:19 UTC, mdahlhausen approved these changes

2024-04-05 18:51 UTC, merged